package com.example.task

const val BUNDLE_KEY_ALBUM = "BUNDLE_KEY_ALBUM"
const val BUNDLE_KEY_FROM_SAVED_FOLDER = "BUNDLE_KEY_FROM_SAVED_FOLDER"
const val BUNDLE_KEY_INFO= "BUNDLE_KEY_INFO"
const val REQUEST_CODE_PERMISSION_WRITE_STORAGE= 23
const val REQUEST_CODE_PERMISSION_LOCATION= 24
const val ZOOM_CHANGE_SIZE= 75
const val KEY_DATA_LOCATION_INFO= "KEY_DATA_LOCATION_INFO"
const val ACTION_INTENT_SEND_LOCATION_INFO= "ACTION_INTENT_SEND_LOCATION_INFO"
const val ACTION_OPEN_LOCATION_ON_NOTIFICATION_CLICK= "ACTION_OPEN_LOCATION_ON_NOTIFICATION_CLICK"
const val BUNDLE_KEY_FROM_NOTIFICATION_CLICK= "BUNDLE_KEY_FROM_NOTIFICATION_CLICK"
const val INTERVAL_LOCATION_REQUEST= 2000L