package com.example.task

const val BUNDLE_KEY_ALBUM = "BUNDLE_KEY_ALBUM"
const val BUNDLE_KEY_FROM_SAVED_FOLDER = "BUNDLE_KEY_FROM_SAVED_FOLDER"
const val BUNDLE_KEY_INFO= "BUNDLE_KEY_INFO"
const val REQUEST_PERMISSION_CODE= 23